apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karakeep.fullname" . }}-web
  labels:
    app.kubernetes.io/component: web
    {{- include "karakeep.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      {{- include "karakeep.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: web
        {{- include "karakeep.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "karakeep.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "karakeep.openaiApiKey" . | trim | nindent 12 }}
            {{- include "karakeep.ollamaConfig" . | trim | nindent 12 }}
            {{- if and .Values.web .Values.web.extraEnv }}
            {{- with .Values.web.extraEnv }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            - name: MEILI_ADDR
              value: http://karakeep-meilisearch:7700
            - name: BROWSER_WEB_URL
              value: http://{{ include "karakeep.fullname" . }}-chrome:9222
            - name: DATA_DIR
              value: {{ include "karakeep.persistenceVolumeMountPath" . }}
            - name: NEXTAUTH_URL
              value: {{ include "karakeep.nextAuthURL" . }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.nextAuthSecret "nextauth-secret" }}
                  key: secret
          {{- if and .Values.web .Values.web.envFrom }}
          envFrom:
            {{- toYaml .Values.web.envFrom | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: {{ include "karakeep.persistenceVolumeName" . }}
              mountPath: {{ include "karakeep.persistenceVolumeMountPath" . }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: {{ include "karakeep.persistenceVolumeName" . }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "karakeep.persistenceVolumeName" . }}{{- end }}
        {{- else }}
        - name: {{ include "karakeep.persistenceVolumeName" . }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
