apiVersion: v1
kind: Service
metadata:
  name: {{ include "karakeep.fullname" . }}-chrome
  labels:
    app.kubernetes.io/component: chrome
    {{- include "karakeep.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9222
      targetPort: remote
      protocol: TCP
      name: remote
  selector:
    app.kubernetes.io/component: chrome
    {{- include "karakeep.selectorLabels" . | nindent 4 }}
